export const FETCH_DECISIONS_BEGIN = "FETCH_DECISIONS_BEGIN";
export const FETCH_DECISIONS_SUCCESS = "FETCH_DECISIONS_SUCCESS";
export const FETCH_DECISIONS_FAILURE = "FETCH_DECISIONS_FAILURE";
export const DECISION_TITLE_CHANGE = "DECISION_TITLE_CHANGE";
export const DECISION_CONTEXT_CHANGE = "DECISION_CONTEXT_CHANGE";
export const CREATE_DECISION = "CREATE_DECISION";

export const CREATE_VARIABLE = "CREATE_VARIABLE";
