export const FETCH_DECISIONS_BEGIN = "FETCH_DECISIONS_BEGIN";
export const FETCH_DECISIONS_SUCCESS = "FETCH_DECISIONS_SUCCESS";
export const FETCH_DECISIONS_FAILURE = "FETCH_DECISIONS_FAILURE";
export const CHANGE_TITLE = "CHANGE_TITLE";
